services:
  - type: web
    name: lavandershopbot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from src.utils.db import init_db; init_db()"
    startCommand: python webhook.py
    envVars:
      - key: BOT_TOKEN
        value: 7313861292:AAEThP2eynTXlRxljyas9Gma_FPvGVVZhT8
      - key: DATABASE_URL
        value: postgresql://admin:z08MOdcHDvaIkTxVqX7HiagLj3sQJk12@dpg-d07r2cp5pdvs73ae65r0-a/shop_sov1