services:
  - type: web
    name: lavandershopbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: BOT_TOKEN
        fromGitHub: false
        value: 7313861292:AAEThP2eynTXlRxljyas9Gma_FPvGVVZhT8
      - key: ADMIN_SECRET
        fromGitHub: false
        value: 1293forever
      - key: DATABASE_URL
        fromGitHub: false
        value: postgresql://admin:z08MOdcHDvaIkTxVqX7HiagLj3sQJk12@dpg-d07r2cp5pdvs73ae65r0-a/shop_sov1